TomasosPizzeriaUppgift/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TomasosPizzeriaUppgift.ViewModels
{
    public class LoginViewModel
    {

        [Required(ErrorMessage = "Användarnamn är obligatoriskt")]
        public string Username { get; set; }


        [Required(ErrorMessage = "Lösenord är obligatoriskt")]
        public string Password { get; set; }

        [Display(Name = "Kom ihåg mig")]
        public bool RememberMe { get; set; }
    }
}

TomasosPizzeriaUppgift/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TomasosPizzeriaUppgift.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TomasosPizzeriaUppgift.Controllers
{
    public class PaymentController : Controller
    {
        // GET: /<controller>/
        [HttpGet]
        [Authorize]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginViewModel model)
        {
            var result = Services.Services.Instance.CheckValidLogin(model);
            if (ModelState.IsValid && result == true)
            {
                return RedirectToAction("Pay");
                
            }

            ViewBag.Error = "Inloggning Misslyckades";
            return View(model);
        }

        [Authorize]
        public IActionResult Pay()
        {
            Services.Services.Instance.PayUser(Request, Response);
            return View();
        }
    }
}

TomasosPizzeriaUppgift/Views/Payment/Login.cshtml
@model LoginViewModel

@{
    ViewBag.Title = "Kund Inloggning";
}

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
<link href="~/css/inloggPageStyle.css" rel="stylesheet" type="text/css" asp-append-version="true" />
<link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
<div class="text-center">

    <form class="login" asp-controller="Payment" asp-action="Login" method="post">
        <span class="failer-login">@ViewBag.Error</span>
        <span class="failer-login" asp-validation-for="Username"></span>
        <input type="text" placeholder="Användarnamn" asp-for="Username">
        <span class="failer-login" asp-validation-for="Password"></span>
        <input type="password" placeholder="Lösenord" asp-for="Password">
        <input class="button" type="submit" value="Betala" />
    </form>

</div>

TomasosPizzeriaUppgift/Views/Payment/Pay.cshtml
@model MenuPage
@{



    Layout = "~/Views/Shared/_Layout.cshtml";


}


<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
<link rel="stylesheet" href="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true" />
<link rel="stylesheet" href="~/lib/jquery/dist/jquery.min.js" asp-append-version="true" />
<link href="~/css/MenuPage.css" rel="stylesheet" type="text/css" asp-append-version="true" />

<div class="d-flex justify-content-center">

    <div class="pay-text">

        <section class="menu-items">
            <h3>Order beställd</h3>
            <h4>Din order är klar om 60 min</h4>

        </section>



    </div>
</div>